# Generated by Django 6.0 on 2025-12-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_quotemessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='full_name',
            field=models.CharField(default='NA', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
